### ISSUE TITLE
GitHub integration with accessToken failing

### ISSUE THREAD

**Issue by lsanchez-v** [JonasHiltl/openchangelog#22]
Hi,

I'm trying to integrate openchangelog (running in a k8s cluster) with one of my company's GitHub repositories to read the CHANGELOG.md file on it, but I'm getting the following error from the pod:

`superfluous response.WriteHeader call from github.com/jonashiltl/openchangelog/internal/handler/web.RegisterWebHandler.serveHTTP.func1 (routes.go:80)`

I'm using the following config:

```
addr: 0.0.0.0:6001
page:
  title: testing title
  subtitle: This page lists all the data releases
  colorScheme: light
  logo:
    src: https://img.icons8.com/?size=100&id=89745&format=png&color=000000
    width: 70px
    height: 25px
    link: https://example.com
github:
  owner: mycompany
  repo: myrepo
  path: CHANGELOG.md
  auth:
    accessToken: ***
```

I'm also giving full "repo" and "project" permissions to the access token.

Any idea what this error could mean? is there any way to enable a more detailed debugging mode?

Thanks.
